version: "3"

services:
  tunnel:
    build:
      context: ./tunnel
      dockerfile: Dockerfile
    volumes:
      # Probably should COPY config instead of mounting
      - ./tunnel/config:/etc/nginx
      - ./web:/var/www/html
    network_mode: host
