version: "3"

volumes:
  # Use shared volume that does not get mounted on host to speed up on mac O(100x) improvement
  gen:
  eyg_gen:
services:
  editor:
    build:
      context: .
      dockerfile: language.Dockerfile
    working_dir: /opt/app
    volumes:
      - .:/opt/app
      - gen:/opt/app/editor/src/gen
      - eyg_gen:/opt/app/eyg/gen
    # network_mode unavailable on mac
    # network_mode: host
    # can't have port here because need to start two services
    # command: "watchexec --exts gleam -- sh build_eyg"
  editor_frontend:
    image: node:16.13.0
    working_dir: /opt/app/editor
    volumes:
      - .:/opt/app
      - gen:/opt/app/editor/src/gen
      # Need to use -p 5000:5000 for access via localhost
    ports:
      - "5000:5000"
    command: "npm run dev"
