version: "3"

volumes:
  _build:
  deps:
  gen:
services:
  spotless:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt/app
    volumes:
      - .:/opt/app
      - _build:/opt/app/_build
      - deps:/opt/app/deps
      # NOTE Issue Gleam shouldn't delete gen directory.
      # - gen:/opt/app/gen
    network_mode: host
    environment:
      PORT: 8080
      ENVIRONMENT: local
