
[build]
base    = ""
publish = "editor/public"
command = """
    wget -c https://github.com/gleam-lang/gleam/releases/download/v0.21.0/gleam-v0.21.0-linux-amd64.tar.gz -O - | tar -xz -C . &&
    (cd eyg && ../gleam build)
    (cd editor && npm install)
    mkdir editor/public/build
    (cd editor && npm run build)
    """
