name = "eyg"
tool = "gleam"
version = "0.1.0"
target = "javascript"
description = "Abstract Syntax Tree tools"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.20"
gleam_javascript = "~> 0.6"
gleam_bitwise = "~> 1.2"
lustre = "~> 3.0"
gleam_json = "~> 0.5"
gleam_fetch = "~> 0.1"
# plinth = "~> 0.1.6"
plinth = {path= "../../plinth"}
simplifile = "~> 1.0"
gleam_http = "~> 3.5"
gleam_community_codec = {path= "../../codec"}


[dev-dependencies]
gleeunit = "~> 1.0"
