name = "eyg"
tool = "gleam"
version = "0.1.0"
target = "javascript"
description = "Abstract Syntax Tree tools"
gleam = ">= 1.5.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 1.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
gleam_bitwise = "~> 1.2"
lustre = "~> 4.0"
gleam_json = ">= 1.0.0 and < 3.0.0"
gleam_fetch = "~> 1.0"
plinth = ">= 0.5.2 and < 1.0.0"
simplifile = "~> 1.0"
gleam_community_codec = {path= "../../codec"}
midas = ">= 1.0.0 and < 2.0.0"
javascript_mutable_reference = ">= 1.0.0 and < 2.0.0"
midas_browser = ">= 0.1.1 and < 1.0.0"
jot = ">= 1.1.0 and < 2.0.0"
midas_sdk = ">= 0.2.0 and < 1.0.0"
oas = ">= 1.0.1 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
glen_node = ">= 0.0.2 and < 1.0.0"
glen = ">= 2.2.1 and < 3.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
midas_node = ">= 1.2.0 and < 2.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
supa = ">= 1.0.0 and < 2.0.0"
mysig = ">= 0.4.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
