name = "eyg_hub"
version = "0.1.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
dag_json = ">= 3.0.0 and < 4.0.0"
eyg_analysis = { path = "../gleam_analysis" }
eyg_interpreter = { path = "../gleam_interpreter" }
eyg_ir = { path = "../gleam_ir" }
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
midas = ">= 3.0.0 and < 4.0.0"
multiformats = ">= 4.0.0 and < 5.0.0"
ogre = ">= 1.1.0 and < 2.0.0"
untethered = { path = "../untethered" }

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_crypto = ">= 1.6.0 and < 2.0.0"
