name = "overlay_llm"
version = "0.2.0"

description = "An API for LLM completion that unifies across different providers."
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "eyg-lang", path = "packages/overlay_llm", tag_prefix = "overlay_llm-"  }
links = [{ title = "EYG", href = "https://eyg.run/overlay" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
castor = ">= 2.0.0 and < 3.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
midas = ">= 3.1.0 and < 4.0.0"
oas_generator_utils = ">= 1.1.0 and < 2.0.0"
ogre = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
