name = "loam"
version = "1.0.0"
target = "javascript"

# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
envoy = ">= 1.2.0 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
gleam_crypto = ">= 1.6.0 and < 2.0.0"
gleam_fetch = ">= 1.4.1 and < 2.0.0"
gleam_http = ">= 4.4.0 and < 5.0.0"
gleam_javascript = ">= 1.0.1 and < 2.0.0"
gleam_x = { path = "../gleam_x" }
kryptos = ">= 1.5.0 and < 2.0.0"
midas = ">= 3.1.0 and < 4.0.0"
multiformats = ">= 4.0.0 and < 5.0.0"
shellout = ">= 1.8.0 and < 2.0.0"
simplifile = ">= 2.7.0 and < 3.0.0"
untethered = { path = "../untethered" }

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
