name = "eyg_cli"
version = "0.0.0"
target = "javascript"

description = "CLI for running EYG programs and interacting with the EYG hub."
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "eyg-lang", path = "packages/gleam_cli", tag_prefix = "gleam_cli-" }
links = [{ title = "Website", href = "https://eyg.run" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
envoy = ">= 1.1.0 and < 2.0.0"
eyg_compiler = { path = "../gleam_compiler" }
eyg_hub = { path = "../gleam_hub" }
eyg_interpreter = ">= 1.1.0 and < 2.0.0"
eyg_ir = ">= 1.0.0 and < 2.0.0"
eyg_parser = ">= 0.3.0 and < 1.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
gleam_fetch = ">= 1.4.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_x = { path = "../gleam_x" }
kryptos = ">= 1.3.0 and < 2.0.0"
midas = ">= 2.0.0 and < 3.0.0"
multiformats = ">= 4.0.0 and < 5.0.0"
ogre = ">= 1.1.0 and < 2.0.0"
shellout = ">= 1.8.0 and < 2.0.0"
simplifile = ">= 2.4.0 and < 3.0.0"
snag = ">= 1.2.0 and < 2.0.0"
spotless = ">= 3.4.0 and < 4.0.0"
touch_grass = ">= 0.1.0 and < 1.0.0"
untethered = { path = "../untethered" }

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript]
runtime = "bun"
