name = "overlay"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
castor = ">= 2.1.0 and < 3.0.0"
eyg_analysis = ">= 2.1.0 and < 3.0.0"
eyg_interpreter = ">= 8.0.0 and < 9.0.0"
gleam_http = ">= 4.4.0 and < 5.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
oas_generator_utils = ">= 1.1.0 and < 2.0.0"
ogre = ">= 1.2.0 and < 2.0.0"
overlay_llm = { path = "../overlay_llm" }
touch_grass = { path = "../touch_grass" }

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
