name = "eyg_ir"
version = "1.0.0"
target = "javascript"

description = "Data structures for the EYG IR"
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "eyg-lang", path = "packages/gleam_ir", tag_prefix = "gleam_ir-" }
links = [{ title = "Website", href = "https://eyg.run" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
dag_json = ">= 3.0.0 and < 4.0.0"
multiformats = ">= 4.0.0 and < 5.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
