name = "morph"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
eyg_ir = {path = "../gleam_ir"}
eyg_interpreter = {path = "../gleam_interpreter"}
eyg_analysis = {path = "../gleam_analysis"}
gleamx = {path = "../gleamx"}
plinth = ">= 0.5.8 and < 1.0.0"
lustre = ">= 4.6.4 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
