[build]
# use an eyg shell script here, install binary runner
# builds easel in the eyg directory
command = """
  cd ../eyg && 
  wget -c https://github.com/gleam-lang/gleam/releases/download/v0.28.3/gleam-v0.28.3-x86_64-unknown-linux-musl.tar.gz -O - | tar -xz -C . &&
  ./gleam --version &&
  ./gleam build &&
  ls . &&
  ls ./build &&
  npx rollup -f iife -i ./public/easel.js -o ../website/build/easel.js &&
  cd ../website
  cp -R public/* build/
  """
publish = "build"