[build]
# use an eyg shell script here, install binary runner
# builds easel in the eyg directory
command = """
  cd eyg && 
  wget -c https://github.com/gleam-lang/gleam/releases/download/v0.30.5/gleam-v0.30.5-x86_64-unknown-linux-musl.tar.gz -O - | tar -xz -C . &&
  ./gleam --version &&
  ./gleam build &&
  npm i
  npx rollup -f iife -i ./public/easel.js -o ../website/build/easel.js &&

  echo 'eyg built' &&

  ./gleam run cli cozo ./saved/saved.json &&
  cd .. &&
  mkdir cozy/build &&
  cp wisdom/tmp.db.json cozy/build/db.json &&
  (cd cozy;
    npm i &&
    npx rollup --config rollup.config.mjs && 
    cp index.html build/index.html && 
    cp node_modules/cozo-lib-wasm/cozo_lib_wasm_bg.wasm build 
  ) &&

  cd website &&
  mkdir build/explore &&
  cp -R ../cozy/build build/explore &&
  cp -R public/* build/
  """
publish = "website/build"