name: test

on:
  push:
    branches:
  pull_request:

env:
  POSTGRES_PASSWORD: banana-penguin-truck
  SECRET_KEY_BASE: word-button-noodle

jobs:
  test-beam:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gleam: ["1.15.3"]
        otp: ["28.4"]
        rebar3: ["3.25"]
        package: [
          "gleam_analysis",
          "gleam_hub",
          "gleam_ir",
          "gleam_parser",
          "topological",
          "touch_grass",
          "untethered"
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          gleam-version: ${{matrix.gleam}}
          rebar3-version: ${{matrix.rebar3}}
      - run: gleam deps download
        shell: bash # Required for git deps
        working-directory: packages/${{matrix.package}}
      - run: gleam build --warnings-as-errors
        working-directory: packages/${{matrix.package}}
      - run: gleam test
        working-directory: packages/${{matrix.package}}
      - run: gleam format --check src test
        working-directory: packages/${{matrix.package}}
  test-db:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gleam: ["1.15.3"]
        otp: ["28.4"]
        rebar3: ["3.25"]
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          gleam-version: ${{matrix.gleam}}
          rebar3-version: ${{matrix.rebar3}}
      - run: gleam build --warnings-as-errors
        working-directory: packages/hub  
      - run: gleam dev migrate
        working-directory: packages/hub  
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          SECRET_KEY_BASE: ${{ env.SECRET_KEY_BASE }}
      - run: gleam test
        working-directory: packages/hub  
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          SECRET_KEY_BASE: ${{ env.SECRET_KEY_BASE }}
  test-bun:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gleam: ["1.15.3"]
        otp: ["28.4"]
        bun: ["1.3.10",]
        package: [
          "eyg_check",
          "gleam_analysis",
          "gleam_cli",
          "gleam_compiler",
          "gleam_hub",
          "gleam_ir",
          "gleam_interpreter",
          "gleam_parser",
          "gleam_x",
          "morph",
          "topological",
          "touch_grass",
          "untethered",
          "website"
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{matrix.bun}}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          gleam-version: ${{matrix.gleam}}
      - run: gleam deps download
        shell: bash # Required for git deps
        working-directory: packages/${{matrix.package}}
      - run: gleam build --target javascript --warnings-as-errors
        working-directory: packages/${{matrix.package}}
      - run: gleam test --target javascript --runtime bun
        working-directory: packages/${{matrix.package}}
      - run: gleam format --check src test
        working-directory: packages/${{matrix.package}}