name: test

on:
  push:
    branches:
  pull_request:

jobs:
  test-beam:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gleam: ["1.15.2"]
        otp: ["28.4"]
        rebar3: ["3.25"]
        package: ["gleam_ir", "gleam_parser", "touch_grass"]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          gleam-version: ${{matrix.gleam}}
          rebar3-version: ${{matrix.rebar3}}
      - run: gleam deps download
        shell: bash # Required for git deps
        working-directory: packages/${{matrix.package}}
      - run: gleam build --warnings-as-errors
        working-directory: packages/${{matrix.package}}
      - run: gleam test
        working-directory: packages/${{matrix.package}}
      - run: gleam format --check src test
        working-directory: packages/${{matrix.package}}
  test-bun:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gleam: ["1.15.2"]
        otp: ["28.4"]
        bun: ["1.3.10",]
        package: ["gleam_ir", "gleam_interpreter", "gleam_parser", "touch_grass"]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{matrix.bun}}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          gleam-version: ${{matrix.gleam}}
      - run: gleam deps download
        shell: bash # Required for git deps
        working-directory: packages/${{matrix.package}}
      - run: gleam build --target javascript --warnings-as-errors
        working-directory: packages/${{matrix.package}}
      - run: gleam test --target javascript --runtime bun
        working-directory: packages/${{matrix.package}}
      - run: gleam format --check src test
        working-directory: packages/${{matrix.package}}